version: '3.8'

services:
  #app services

  frontend:
    build:
      context: ./client/
      target: development
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend:server
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
  
  backend:
    build:
      context: ./server/
      target: development
      args:
        - NODE_ENV=production
        - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
        - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
        - PORT=3001
        - CLIENT_PORT=80
        - TZ=Europe/Rome
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - 3001:3001
    environment:
      NODEMAILER_EMAIL: ${NODEMAILER_EMAIL}
      NODEMAILER_PASSWORD: ${NODEMAILER_PASSWORD}
      PORT: 3001
      CLIENT_PORT: 3000
      TZ: Europe/Rome
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"