name: Build Docker Images CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: code

    steps:
    - name: Build Docker images
      uses: actions/checkout@v3
      
    - run: docker-compose -f docker-compose.prod.yml build
