name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: code

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker images
    - run: docker-compose -f docker-compose.prod.yml build
    - run: docker-compose -f docker-compose.prod.yml push
